# Generated by Django 4.1.1 on 2022-12-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
