# Generated by Django 4.1.1 on 2022-12-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gravedad',
            field=models.CharField(default='Minima', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('Minima', 'Minima'), ('Media', 'Media'), ('Alta', 'Alta')], default='Minima', max_length=30),
        ),
    ]
