# Generated by Django 4.1.1 on 2022-12-15 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('Minima', 'Minima'), ('Media', 'Media'), ('Alta', 'Alta')], default='No Atendido', max_length=30),
        ),
    ]
