# Generated by Django 4.1.1 on 2022-12-15 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_ticket_fecha_creacion_alter_ticket_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTicket', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('emisor', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='ticket',
            name='emisor',
            field=models.CharField(default='Usuario', max_length=50),
        ),
    ]
