# Generated by Django 4.1.1 on 2022-12-15 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_ticket_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='03:46:46'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='03:46:46'),
        ),
    ]
