# Generated by Django 4.1.1 on 2022-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_alter_respuesta_fecha_alter_respuesta_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='05:05:33'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='No Atendido', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gravedad',
            field=models.CharField(choices=[('Minima', 'Minima'), ('Media', 'Media'), ('Alta', 'Alta')], default='Minima', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='05:05:33'),
        ),
    ]
