# Generated by Django 4.1.1 on 2022-12-26 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0010_alter_respuesta_hora_alter_ticket_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='17:46:52'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='idTicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='17:46:52'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
