# Generated by Django 4.1.1 on 2022-12-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0011_alter_respuesta_fecha_alter_respuesta_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='17:47:25'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='17:47:25'),
        ),
    ]
