# Generated by Django 4.1.1 on 2022-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0017_alter_respuesta_hora_alter_ticket_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='18:38:50'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='18:38:50'),
        ),
    ]
