# Generated by Django 4.1.1 on 2022-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0018_alter_respuesta_hora_alter_respuesta_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='idTicket',
            new_name='Ticket',
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='18:44:47'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='18:44:47'),
        ),
    ]
