# Generated by Django 4.1.1 on 2022-12-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0019_rename_idticket_respuesta_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='18:52:46'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='18:52:46'),
        ),
    ]
