# Generated by Django 4.1.1 on 2022-12-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0021_alter_respuesta_ticket_alter_respuesta_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='hora',
            field=models.TimeField(default='19:28:18'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(default='19:28:18'),
        ),
    ]
